import { useState } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle, XCircle, Droplets, Download } from "lucide-react";
import { apiRequest } from "@/lib/queryClient";
import type { DietPlan, CKDAssessment } from "@shared/schema";

interface DietPlanProps {
  params: { id: string };
}

export default function DietPlan({ params }: DietPlanProps) {
  const assessmentId = parseInt(params.id);
  const [dietType, setDietType] = useState<'vegetarian' | 'non-vegetarian'>('vegetarian');

  const { data: assessment } = useQuery<CKDAssessment>({
    queryKey: ["/api/ckd-assessment", assessmentId],
    enabled: !isNaN(assessmentId),
  });

  const dietPlanMutation = useMutation({
    mutationFn: async ({ assessmentId, dietType }: { assessmentId: number, dietType: string }) => {
      const response = await apiRequest("POST", "/api/diet-plan", { assessmentId, dietType });
      return response.json();
    },
  });

  const { data: dietPlan, isLoading } = useQuery<DietPlan>({
    queryKey: ["/api/diet-plan", assessmentId, dietType],
    queryFn: () => dietPlanMutation.mutateAsync({ assessmentId, dietType }),
    enabled: !isNaN(assessmentId),
  });

  const toggleDietType = (type: 'vegetarian' | 'non-vegetarian') => {
    setDietType(type);
  };

  const downloadDietPlan = () => {
    if (!dietPlan) return;

    const foodsToEat = JSON.parse(dietPlan.foodsToEat);
    const foodsToAvoid = JSON.parse(dietPlan.foodsToAvoid);

    const planText = `
Personalized CKD Diet Plan (${dietType})
=======================================

Based on your CKD risk assessment, here are personalized dietary recommendations:

FOODS TO EAT:
${foodsToEat.map((food: string) => `✓ ${food}`).join('\n')}

FOODS TO AVOID:
${foodsToAvoid.map((food: string) => `✗ ${food}`).join('\n')}

WATER INTAKE ADVICE:
${dietPlan.waterIntakeAdvice}

IMPORTANT NOTES:
- This diet plan is based on your CKD risk assessment results
- Always consult with a registered dietitian or healthcare provider before making significant dietary changes
- Monitor your kidney function regularly and adjust diet as recommended by your healthcare team
- This plan is for informational purposes only and should not replace professional medical advice

Generated by NephroCare
    `;

    const blob = new Blob([planText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `ckd-diet-plan-${dietType}-${assessmentId}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="flex justify-center items-center min-h-96">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    );
  }

  const foodsToEat = dietPlan ? JSON.parse(dietPlan.foodsToEat) : [];
  const foodsToAvoid = dietPlan ? JSON.parse(dietPlan.foodsToAvoid) : [];

  return (
    <div className="max-w-4xl mx-auto">
      <Card>
        <CardHeader className="text-center">
          <CardTitle className="text-3xl font-bold">Personalized Diet Plan</CardTitle>
          <p className="text-gray-600">
            Based on your CKD risk assessment and analysis of your health parameters
          </p>
        </CardHeader>
        <CardContent>
          {/* Diet Type Toggle */}
          <div className="flex justify-center mb-8">
            <div className="bg-gray-100 p-1 rounded-lg">
              <Button
                variant={dietType === 'vegetarian' ? 'default' : 'ghost'}
                onClick={() => toggleDietType('vegetarian')}
                className="px-6 py-2"
              >
                Vegetarian
              </Button>
              <Button
                variant={dietType === 'non-vegetarian' ? 'default' : 'ghost'}
                onClick={() => toggleDietType('non-vegetarian')}
                className="px-6 py-2"
              >
                Non-Vegetarian
              </Button>
            </div>
          </div>

          {/* Diet Content */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
            {/* Foods to Eat */}
            <Card className="border-green-200 bg-green-50">
              <CardHeader>
                <CardTitle className="flex items-center text-green-800">
                  <CheckCircle className="mr-3 h-5 w-5" />
                  Foods to Eat
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-3 text-green-700">
                  {foodsToEat.map((food: string, index: number) => (
                    <li key={index} className="flex items-start">
                      <CheckCircle className="h-4 w-4 text-green-500 mt-0.5 mr-2 flex-shrink-0" />
                      <span className="text-sm">{food}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>

            {/* Foods to Avoid */}
            <Card className="border-red-200 bg-red-50">
              <CardHeader>
                <CardTitle className="flex items-center text-red-800">
                  <XCircle className="mr-3 h-5 w-5" />
                  Foods to Avoid
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="space-y-3 text-red-700">
                  {foodsToAvoid.map((food: string, index: number) => (
                    <li key={index} className="flex items-start">
                      <XCircle className="h-4 w-4 text-red-500 mt-0.5 mr-2 flex-shrink-0" />
                      <span className="text-sm">{food}</span>
                    </li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </div>

          {/* Water Intake Advice */}
          <Card className="border-blue-200 bg-blue-50 mb-8">
            <CardHeader>
              <CardTitle className="flex items-center text-blue-800">
                <Droplets className="mr-3 h-5 w-5" />
                Water Intake Advice
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="text-blue-700">
                {dietPlan?.waterIntakeAdvice.split('. ').map((sentence, index) => (
                  <p key={index} className="mb-2">
                    <strong>{sentence.split(':')[0]}:</strong> {sentence.split(':').slice(1).join(':')}
                  </p>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Download Button */}
          <div className="text-center">
            <Button size="lg" onClick={downloadDietPlan} className="px-8 py-4 text-lg">
              <Download className="mr-3 h-5 w-5" />
              Download Diet Plan
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
